### ISSUE TITLE
MAIN_PR004767 13MD05-90_1_20_VMEcardsInMDISwizard

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#19] opened 2018-07-23 12:01 UTC
_From @michaelmiehling on June 28, 2018 9:38_

**Describe the bug**
1. MDIS Wizard does not recognize new directory structure of VME4L_PLDZ002 driver

2. A25 Standard board is not available in MDIS Wizard

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20

**Additional context**
![vmeerrormdiswizard](https://user-images.githubusercontent.com/23742250/42026584-c4068d30-7ac7-11e8-9a90-2c90176ebe75.PNG)

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#17_

**Comment by KonradJPE** [comment] 2018-10-11 10:12
1. Path was corrected, now VME4L_PLDZ002 can be added successfully.
2. This is duplicate of issue #36.

**Closed as completed** 2018-10-11 10:12 UTC
Labels: bug
